#include <LiquidCrystal.h>
LiquidCrystal lcd(13,12,11,10,9,8); 

int on=0; //interrupcion 0
int cont; //interrupcion 1
String dato;
float dinero;
float total;
int j=0;

void setup() {
  lcd.begin(16,2);
  Serial.begin(9600);
  attachInterrupt(0,activacion,LOW);
  attachInterrupt(1,modo,LOW);
}

void loop() {
  if(on==0){
    while(j<1){
      lcd.clear();
      j++;
    }
   if(cont==0){
    while(j<1){
      lcd.clear();
      j++;
    }
    if(Serial.available()>0){
      dato=Serial.readString();
      dinero=dato.toInt();
    }
    total=dinero*1;
    lcd.setCursor(0,0);
    lcd.print("EURO:");
    lcd.setCursor(8,0);
    lcd.print(dinero);
    lcd.setCursor(0,1);
    lcd.print("EURO:");
    lcd.setCursor(8,1);
    lcd.print(total);
   }
   if(cont==1){
    while(j<1){
      lcd.clear();
      j++;
    }
    if(Serial.available()>0){
      dato=Serial.readString();
      dinero=dato.toInt();
    }
    total=dinero*1.25;
    lcd.setCursor(0,0);
    lcd.print("EURO: ");
    lcd.setCursor(8,0);
    lcd.print(dinero);
    lcd.setCursor(0,1);
    lcd.print("DOLAR: ");
    lcd.setCursor(8,1);
    lcd.print(total);
   }
   if(cont==2){
    while(j<1){
      lcd.clear();
      j++;
    }
    if(Serial.available()>0){
      dato=Serial.readString();
      dinero=dato.toInt();
    }
    total=dinero*4202.26;
    lcd.setCursor(0,0);
    lcd.print("EURO:");
    lcd.setCursor(8,0);
    lcd.print(dinero);
    lcd.setCursor(0,1);
    lcd.print("PES.COL:");
    lcd.setCursor(8,1);
    lcd.print(total);
   }
   if(cont==3){
    while(j<1){
      lcd.clear();
      j++;
    }
    if(Serial.available()>0){
      dato=Serial.readString();
      dinero=dato.toInt();
    }
    total=dinero*1.08;
    lcd.setCursor(0,0);
    lcd.print("EURO:");
    lcd.setCursor(8,0);
    lcd.print(dinero);
    lcd.setCursor(0,1);
    lcd.print("FRAN.SUI:");
    lcd.setCursor(8,1);
    lcd.print(total);
   }
   if(cont==4){
    while(j<1){
      lcd.clear();
      j++;
    }
    if(Serial.available()>0){
      dato=Serial.readString();
      dinero=dato.toInt();
    }
    total=dinero*98.99;
    lcd.setCursor(0,0);
    lcd.print("EURO:");
    lcd.setCursor(8,0);
    lcd.print(dinero);
    lcd.setCursor(0,1);
    lcd.print("PES.ARG:");
    lcd.setCursor(8,1);
    lcd.print(total);
   }
  }
//***********************************Dolares************************************
  if(on==1){
    while(j<1){
      lcd.clear();
      j++;
    }
   if(cont==0){
    while(j<1){
      lcd.clear();
      j++;
    }
    if(Serial.available()>0){
      dato=Serial.readString();
      dinero=dato.toInt();
    }
    total=dinero*0.82;
    lcd.setCursor(0,0);
    lcd.print("DOLAR:");
    lcd.setCursor(8,0);
    lcd.print(dinero);
    lcd.setCursor(0,1);
    lcd.print("EURO:");
    lcd.setCursor(8,1);
    lcd.print(total);
   }
   if(cont==1){
    while(j<1){
      lcd.clear();
      j++;
    }
    if(Serial.available()>0){
      dato=Serial.readString();
      dinero=dato.toInt();
    }
    total=dinero*1;
    lcd.setCursor(0,0);
    lcd.print("DOLAR:");
    lcd.setCursor(8,0);
    lcd.print(dinero);
    lcd.setCursor(0,1);
    lcd.print("DOLAR: ");
    lcd.setCursor(8,1);
    lcd.print(total);
   }
   if(cont==2){
    while(j<1){
      lcd.clear();
      j++;
    }
    if(Serial.available()>0){
      dato=Serial.readString();
      dinero=dato.toInt();
    }
    total=dinero*3466.50;
    lcd.setCursor(0,0);
    lcd.print("DOLAR:");
    lcd.setCursor(8,0);
    lcd.print(dinero);
    lcd.setCursor(0,1);
    lcd.print("PES.COL:");
    lcd.setCursor(8,1);
    lcd.print(total);
   }
   if(cont==3){
    while(j<1){
      lcd.clear();
      j++;
    }
    if(Serial.available()>0){
      dato=Serial.readString();
      dinero=dato.toInt();
    }
    total=dinero*3.58;
    lcd.setCursor(0,0);
    lcd.print("DOLAR:");
    lcd.setCursor(8,0);
    lcd.print(dinero);
    lcd.setCursor(0,1);
    lcd.print("FRAN.SUI:");
    lcd.setCursor(8,1);
    lcd.print(total);
   }
   if(cont==4){
    while(j<1){
      lcd.clear();
      j++;
    }
    if(Serial.available()>0){
      dato=Serial.readString();
      dinero=dato.toInt();
    }
    total=dinero*81.66;
    lcd.setCursor(0,0);
    lcd.print("DOLAR:");
    lcd.setCursor(8,0);
    lcd.print(dinero);
    lcd.setCursor(0,1);
    lcd.print("PES.ARG:");
    lcd.setCursor(8,1);
    lcd.print(total);
   }
  }

//***********************************FRANCO SUIZO************************************
  if(on==2){
    while(j<1){
      lcd.clear();
      j++;
    }
   if(cont==0){
    while(j<1){
      lcd.clear();
      j++;
    }
    if(Serial.available()>0){
      dato=Serial.readString();
      dinero=dato.toInt();
    }
    total=dinero*0.23;
    lcd.setCursor(0,0);
    lcd.print("FRAN.SUI:");
    lcd.setCursor(9,0);
    lcd.print(dinero);
    lcd.setCursor(0,1);
    lcd.print("EURO:");
    lcd.setCursor(9,1);
    lcd.print(total);
   }
   if(cont==1){
    while(j<1){
      lcd.clear();
      j++;
    }
    if(Serial.available()>0){
      dato=Serial.readString();
      dinero=dato.toInt();
    }
    total=dinero*0.28;
    lcd.setCursor(0,0);
    lcd.print("FRAN.SUI:");
    lcd.setCursor(9,0);
    lcd.print(dinero);
    lcd.setCursor(0,1);
    lcd.print("DOLAR:");
    lcd.setCursor(9,1);
    lcd.print(total);
   }
   if(cont==2){
    while(j<1){
      lcd.clear();
      j++;
    }
    if(Serial.available()>0){
      dato=Serial.readString();
      dinero=dato.toInt();
    }
    total=dinero*965.38;
    lcd.setCursor(0,0);
    lcd.print("FRAN.SUI:");
    lcd.setCursor(9,0);
    lcd.print(dinero);
    lcd.setCursor(0,1);
    lcd.print("PES.COL:");
    lcd.setCursor(9,1);
    lcd.print(total);
   }
   if(cont==3){
    while(j<1){
      lcd.clear();
      j++;
    }
    if(Serial.available()>0){
      dato=Serial.readString();
      dinero=dato.toInt();
    }
    total=dinero*1;
    lcd.setCursor(0,0);
    lcd.print("FRAN.SUI:");
    lcd.setCursor(9,0);
    lcd.print(dinero);
    lcd.setCursor(0,1);
    lcd.print("FRAN.SUI:");
    lcd.setCursor(9,1);
    lcd.print(total);
   }
   if(cont==4){
    while(j<1){
      lcd.clear();
      j++;
    }
    if(Serial.available()>0){
      dato=Serial.readString();
      dinero=dato.toInt();
    }
    total=dinero*22.73;
    lcd.setCursor(0,0);
    lcd.print("FRAN.SUI:");
    lcd.setCursor(9,0);
    lcd.print(dinero);
    lcd.setCursor(0,1);
    lcd.print("PES.ARG:");
    lcd.setCursor(9,1);
    lcd.print(total);
   }
  }
//***********************************PESO COLOMBIANO************************************
  if(on==3){
    while(j<1){
      lcd.clear();
      j++;
    }
   if(cont==0){
    while(j<1){
      lcd.clear();
      j++;
    }
    if(Serial.available()>0){
      dato=Serial.readString();
      dinero=dato.toInt();
    }
    total=dinero*0.00024;
    lcd.setCursor(0,0);
    lcd.print("PES.COL:");
    lcd.setCursor(9,0);
    lcd.print(dinero);
    lcd.setCursor(0,1);
    lcd.print("EURO:");
    lcd.setCursor(9,1);
    lcd.print(total);
   }
   if(cont==1){
    while(j<1){
      lcd.clear();
      j++;
    }
    if(Serial.available()>0){
      dato=Serial.readString();
      dinero=dato.toInt();
    }
    total=dinero*0.00029;
    lcd.setCursor(0,0);
    lcd.print("PES.COL:");
    lcd.setCursor(9,0);
    lcd.print(dinero);
    lcd.setCursor(0,1);
    lcd.print("DOLAR:");
    lcd.setCursor(9,1);
    lcd.print(total);
   }
   if(cont==2){
    while(j<1){
      lcd.clear();
      j++;
    }
    if(Serial.available()>0){
      dato=Serial.readString();
      dinero=dato.toInt();
    }
    total=dinero*1;
    lcd.setCursor(0,0);
    lcd.print("PES.COL:");
    lcd.setCursor(9,0);
    lcd.print(dinero);
    lcd.setCursor(0,1);
    lcd.print("PES.COL:");
    lcd.setCursor(9,1);
    lcd.print(total);
   }
   if(cont==3){
    while(j<1){
      lcd.clear();
      j++;
    }
    if(Serial.available()>0){
      dato=Serial.readString();
      dinero=dato.toInt();
    }
    total=dinero*0.001;
    lcd.setCursor(0,0);
    lcd.print("PES.COL:");
    lcd.setCursor(9,0);
    lcd.print(dinero);
    lcd.setCursor(0,1);
    lcd.print("FRAN.SUI:");
    lcd.setCursor(9,1);
    lcd.print(total);
   }
   if(cont==4){
    while(j<1){
      lcd.clear();
      j++;
    }
    if(Serial.available()>0){
      dato=Serial.readString();
      dinero=dato.toInt();
    }
    total=dinero*0.023;
    lcd.setCursor(0,0);
    lcd.print("PES.COL:");
    lcd.setCursor(9,0);
    lcd.print(dinero);
    lcd.setCursor(0,1);
    lcd.print("PES.ARG:");
    lcd.setCursor(9,1);
    lcd.print(total);
   }
  }
//***********************************PESO ARGENTINO************************************
  if(on==4){
    while(j<1){
      lcd.clear();
      j++;
    }
   if(cont==0){
    while(j<1){
      lcd.clear();
      j++;
    }
    if(Serial.available()>0){
      dato=Serial.readString();
      dinero=dato.toInt();
    }
    total=dinero*0.01;
    lcd.setCursor(0,0);
    lcd.print("PES.ARG:");
    lcd.setCursor(9,0);
    lcd.print(dinero);
    lcd.setCursor(0,1);
    lcd.print("EURO:");
    lcd.setCursor(9,1);
    lcd.print(total);
   }
   if(cont==1){
    while(j<1){
      lcd.clear();
      j++;
    }
    if(Serial.available()>0){
      dato=Serial.readString();
      dinero=dato.toInt();
    }
    total=dinero*0.12;
    lcd.setCursor(0,0);
    lcd.print("PES.ARG:");
    lcd.setCursor(9,0);
    lcd.print(dinero);
    lcd.setCursor(0,1);
    lcd.print("DOLAR:");
    lcd.setCursor(9,1);
    lcd.print(total);
   }
   if(cont==2){
    while(j<1){
      lcd.clear();
      j++;
    }
    if(Serial.available()>0){
      dato=Serial.readString();
      dinero=dato.toInt();
    }
    total=dinero*42.45;
    lcd.setCursor(0,0);
    lcd.print("PES.ARG:");
    lcd.setCursor(9,0);
    lcd.print(dinero);
    lcd.setCursor(0,1);
    lcd.print("PES.COL:");
    lcd.setCursor(9,1);
    lcd.print(total);
   }
   if(cont==3){
    while(j<1){
      lcd.clear();
      j++;
    }
    if(Serial.available()>0){
      dato=Serial.readString();
      dinero=dato.toInt();
    }
    total=dinero*0.044;
    lcd.setCursor(0,0);
    lcd.print("PES.ARG:");
    lcd.setCursor(9,0);
    lcd.print(dinero);
    lcd.setCursor(0,1);
    lcd.print("FRAN.SUI:");
    lcd.setCursor(9,1);
    lcd.print(total);
   }
   if(cont==4){
    while(j<1){
      lcd.clear();
      j++;
    }
    if(Serial.available()>0){
      dato=Serial.readString();
      dinero=dato.toInt();
    }
    total=dinero*1;
    lcd.setCursor(0,0);
    lcd.print("PES.ARG:");
    lcd.setCursor(9,0);
    lcd.print(dinero);
    lcd.setCursor(0,1);
    lcd.print("PES.ARG:");
    lcd.setCursor(9,1);
    lcd.print(total);
   }
  }

}

void activacion(){
  // NO FUNCIONA DELAY
  switch(on){
    case 0:
      Serial.println("");
      Serial.println("CONVERSOR DOLARES");
      on++;
      j=0;
    break;
    case 1:
      Serial.println("");
      Serial.println("CONVERSOR FRANCO SUIZO");
      on++;
      j=0;
    break;
    case 2:
      Serial.println("");
      Serial.println("CONVERSOR PESO COLOMBIANO");
      on++;
      j=0;
    break;
    case 3:
      Serial.println("");
      Serial.println("CONVERSOR PESO ARGENTINO");
      on++;
      j=0;
    break;
    case 4:
      Serial.println("");
      Serial.println("CONVERSOR EURO");
      on=0;
      j=0;
    break;
  }
}

void modo(){
  switch(cont){
    case 0:
      Serial.println("A DOLARES");
      cont++;
      j=0;
    break;
    case 1:
      Serial.println("A PESO COLOMBIANO");
      cont++;
      j=0;
    break;
    case 2:
      Serial.println("A FRANCO SUIZO");
      cont++;
      j=0;
    break;
    case 3:
      Serial.println("A PESO ARGENTINO");
      cont++;
      j=0;
    break;
    case 4:
      cont=0;
      j=0;
    break;
  }
}
/*
 * 1 DOLAR = 1.25 EUROS
 * 1 EURO = 4202.26 EUROS
 * 1 EURO = 1.08 FRANCOS ZUIZOS
 * 1 EURO = 98.99 PESOS ARGENTINOS
 * 1 DOLAR = 0.82 EUROS
 */
